// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: WSMsg.proto

package top.pin90.friend.chatserver.protocol;

public final class WSMsg {
  private WSMsg() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface MsgOrBuilder extends
      // @@protoc_insertion_point(interface_extends:protocol.Msg)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 是要进行的操作
     * </pre>
     *
     * <code>optional int32 ops = 1;</code>
     * @return Whether the ops field is set.
     */
    boolean hasOps();
    /**
     * <pre>
     * 是要进行的操作
     * </pre>
     *
     * <code>optional int32 ops = 1;</code>
     * @return The ops.
     */
    int getOps();

    /**
     * <code>optional int32 code = 2;</code>
     * @return Whether the code field is set.
     */
    boolean hasCode();
    /**
     * <code>optional int32 code = 2;</code>
     * @return The code.
     */
    int getCode();

    /**
     * <code>optional string msg = 3;</code>
     * @return Whether the msg field is set.
     */
    boolean hasMsg();
    /**
     * <code>optional string msg = 3;</code>
     * @return The msg.
     */
    java.lang.String getMsg();
    /**
     * <code>optional string msg = 3;</code>
     * @return The bytes for msg.
     */
    com.google.protobuf.ByteString
        getMsgBytes();

    /**
     * <pre>
     * 消息的目标
     * </pre>
     *
     * <code>optional string target = 5;</code>
     * @return Whether the target field is set.
     */
    boolean hasTarget();
    /**
     * <pre>
     * 消息的目标
     * </pre>
     *
     * <code>optional string target = 5;</code>
     * @return The target.
     */
    java.lang.String getTarget();
    /**
     * <pre>
     * 消息的目标
     * </pre>
     *
     * <code>optional string target = 5;</code>
     * @return The bytes for target.
     */
    com.google.protobuf.ByteString
        getTargetBytes();

    /**
     * <pre>
     *消息的唯一标识符
     * </pre>
     *
     * <code>optional string msg_id = 6;</code>
     * @return Whether the msgId field is set.
     */
    boolean hasMsgId();
    /**
     * <pre>
     *消息的唯一标识符
     * </pre>
     *
     * <code>optional string msg_id = 6;</code>
     * @return The msgId.
     */
    java.lang.String getMsgId();
    /**
     * <pre>
     *消息的唯一标识符
     * </pre>
     *
     * <code>optional string msg_id = 6;</code>
     * @return The bytes for msgId.
     */
    com.google.protobuf.ByteString
        getMsgIdBytes();

    /**
     * <pre>
     * 扩展字段
     * </pre>
     *
     * <code>optional string extend = 7;</code>
     * @return Whether the extend field is set.
     */
    boolean hasExtend();
    /**
     * <pre>
     * 扩展字段
     * </pre>
     *
     * <code>optional string extend = 7;</code>
     * @return The extend.
     */
    java.lang.String getExtend();
    /**
     * <pre>
     * 扩展字段
     * </pre>
     *
     * <code>optional string extend = 7;</code>
     * @return The bytes for extend.
     */
    com.google.protobuf.ByteString
        getExtendBytes();

    /**
     * <pre>
     * 内容的类型
     * </pre>
     *
     * <code>optional int32 type = 10;</code>
     * @return Whether the type field is set.
     */
    boolean hasType();
    /**
     * <pre>
     * 内容的类型
     * </pre>
     *
     * <code>optional int32 type = 10;</code>
     * @return The type.
     */
    int getType();

    /**
     * <pre>
     * 字符串内容
     * </pre>
     *
     * <code>optional string content = 15;</code>
     * @return Whether the content field is set.
     */
    boolean hasContent();
    /**
     * <pre>
     * 字符串内容
     * </pre>
     *
     * <code>optional string content = 15;</code>
     * @return The content.
     */
    java.lang.String getContent();
    /**
     * <pre>
     * 字符串内容
     * </pre>
     *
     * <code>optional string content = 15;</code>
     * @return The bytes for content.
     */
    com.google.protobuf.ByteString
        getContentBytes();

    /**
     * <pre>
     * 字节内容
     * </pre>
     *
     * <code>optional bytes bytes_content = 20;</code>
     * @return Whether the bytesContent field is set.
     */
    boolean hasBytesContent();
    /**
     * <pre>
     * 字节内容
     * </pre>
     *
     * <code>optional bytes bytes_content = 20;</code>
     * @return The bytesContent.
     */
    com.google.protobuf.ByteString getBytesContent();
  }
  /**
   * Protobuf type {@code protocol.Msg}
   */
  public static final class Msg extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:protocol.Msg)
      MsgOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Msg.newBuilder() to construct.
    private Msg(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Msg() {
      msg_ = "";
      target_ = "";
      msgId_ = "";
      extend_ = "";
      content_ = "";
      bytesContent_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Msg();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Msg(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              bitField0_ |= 0x00000001;
              ops_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              code_ = input.readInt32();
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              msg_ = bs;
              break;
            }
            case 42: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000008;
              target_ = bs;
              break;
            }
            case 50: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000010;
              msgId_ = bs;
              break;
            }
            case 58: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000020;
              extend_ = bs;
              break;
            }
            case 80: {
              bitField0_ |= 0x00000040;
              type_ = input.readInt32();
              break;
            }
            case 122: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000080;
              content_ = bs;
              break;
            }
            case 162: {
              bitField0_ |= 0x00000100;
              bytesContent_ = input.readBytes();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return top.pin90.friend.chatserver.protocol.WSMsg.internal_static_protocol_Msg_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return top.pin90.friend.chatserver.protocol.WSMsg.internal_static_protocol_Msg_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              top.pin90.friend.chatserver.protocol.WSMsg.Msg.class, top.pin90.friend.chatserver.protocol.WSMsg.Msg.Builder.class);
    }

    private int bitField0_;
    public static final int OPS_FIELD_NUMBER = 1;
    private int ops_;
    /**
     * <pre>
     * 是要进行的操作
     * </pre>
     *
     * <code>optional int32 ops = 1;</code>
     * @return Whether the ops field is set.
     */
    @java.lang.Override
    public boolean hasOps() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <pre>
     * 是要进行的操作
     * </pre>
     *
     * <code>optional int32 ops = 1;</code>
     * @return The ops.
     */
    @java.lang.Override
    public int getOps() {
      return ops_;
    }

    public static final int CODE_FIELD_NUMBER = 2;
    private int code_;
    /**
     * <code>optional int32 code = 2;</code>
     * @return Whether the code field is set.
     */
    @java.lang.Override
    public boolean hasCode() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional int32 code = 2;</code>
     * @return The code.
     */
    @java.lang.Override
    public int getCode() {
      return code_;
    }

    public static final int MSG_FIELD_NUMBER = 3;
    private volatile java.lang.Object msg_;
    /**
     * <code>optional string msg = 3;</code>
     * @return Whether the msg field is set.
     */
    @java.lang.Override
    public boolean hasMsg() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional string msg = 3;</code>
     * @return The msg.
     */
    @java.lang.Override
    public java.lang.String getMsg() {
      java.lang.Object ref = msg_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          msg_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string msg = 3;</code>
     * @return The bytes for msg.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getMsgBytes() {
      java.lang.Object ref = msg_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        msg_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TARGET_FIELD_NUMBER = 5;
    private volatile java.lang.Object target_;
    /**
     * <pre>
     * 消息的目标
     * </pre>
     *
     * <code>optional string target = 5;</code>
     * @return Whether the target field is set.
     */
    @java.lang.Override
    public boolean hasTarget() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <pre>
     * 消息的目标
     * </pre>
     *
     * <code>optional string target = 5;</code>
     * @return The target.
     */
    @java.lang.Override
    public java.lang.String getTarget() {
      java.lang.Object ref = target_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          target_ = s;
        }
        return s;
      }
    }
    /**
     * <pre>
     * 消息的目标
     * </pre>
     *
     * <code>optional string target = 5;</code>
     * @return The bytes for target.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getTargetBytes() {
      java.lang.Object ref = target_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        target_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MSG_ID_FIELD_NUMBER = 6;
    private volatile java.lang.Object msgId_;
    /**
     * <pre>
     *消息的唯一标识符
     * </pre>
     *
     * <code>optional string msg_id = 6;</code>
     * @return Whether the msgId field is set.
     */
    @java.lang.Override
    public boolean hasMsgId() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <pre>
     *消息的唯一标识符
     * </pre>
     *
     * <code>optional string msg_id = 6;</code>
     * @return The msgId.
     */
    @java.lang.Override
    public java.lang.String getMsgId() {
      java.lang.Object ref = msgId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          msgId_ = s;
        }
        return s;
      }
    }
    /**
     * <pre>
     *消息的唯一标识符
     * </pre>
     *
     * <code>optional string msg_id = 6;</code>
     * @return The bytes for msgId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getMsgIdBytes() {
      java.lang.Object ref = msgId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        msgId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int EXTEND_FIELD_NUMBER = 7;
    private volatile java.lang.Object extend_;
    /**
     * <pre>
     * 扩展字段
     * </pre>
     *
     * <code>optional string extend = 7;</code>
     * @return Whether the extend field is set.
     */
    @java.lang.Override
    public boolean hasExtend() {
      return ((bitField0_ & 0x00000020) != 0);
    }
    /**
     * <pre>
     * 扩展字段
     * </pre>
     *
     * <code>optional string extend = 7;</code>
     * @return The extend.
     */
    @java.lang.Override
    public java.lang.String getExtend() {
      java.lang.Object ref = extend_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          extend_ = s;
        }
        return s;
      }
    }
    /**
     * <pre>
     * 扩展字段
     * </pre>
     *
     * <code>optional string extend = 7;</code>
     * @return The bytes for extend.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getExtendBytes() {
      java.lang.Object ref = extend_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        extend_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TYPE_FIELD_NUMBER = 10;
    private int type_;
    /**
     * <pre>
     * 内容的类型
     * </pre>
     *
     * <code>optional int32 type = 10;</code>
     * @return Whether the type field is set.
     */
    @java.lang.Override
    public boolean hasType() {
      return ((bitField0_ & 0x00000040) != 0);
    }
    /**
     * <pre>
     * 内容的类型
     * </pre>
     *
     * <code>optional int32 type = 10;</code>
     * @return The type.
     */
    @java.lang.Override
    public int getType() {
      return type_;
    }

    public static final int CONTENT_FIELD_NUMBER = 15;
    private volatile java.lang.Object content_;
    /**
     * <pre>
     * 字符串内容
     * </pre>
     *
     * <code>optional string content = 15;</code>
     * @return Whether the content field is set.
     */
    @java.lang.Override
    public boolean hasContent() {
      return ((bitField0_ & 0x00000080) != 0);
    }
    /**
     * <pre>
     * 字符串内容
     * </pre>
     *
     * <code>optional string content = 15;</code>
     * @return The content.
     */
    @java.lang.Override
    public java.lang.String getContent() {
      java.lang.Object ref = content_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          content_ = s;
        }
        return s;
      }
    }
    /**
     * <pre>
     * 字符串内容
     * </pre>
     *
     * <code>optional string content = 15;</code>
     * @return The bytes for content.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getContentBytes() {
      java.lang.Object ref = content_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        content_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int BYTES_CONTENT_FIELD_NUMBER = 20;
    private com.google.protobuf.ByteString bytesContent_;
    /**
     * <pre>
     * 字节内容
     * </pre>
     *
     * <code>optional bytes bytes_content = 20;</code>
     * @return Whether the bytesContent field is set.
     */
    @java.lang.Override
    public boolean hasBytesContent() {
      return ((bitField0_ & 0x00000100) != 0);
    }
    /**
     * <pre>
     * 字节内容
     * </pre>
     *
     * <code>optional bytes bytes_content = 20;</code>
     * @return The bytesContent.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getBytesContent() {
      return bytesContent_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeInt32(1, ops_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeInt32(2, code_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, msg_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, target_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, msgId_);
      }
      if (((bitField0_ & 0x00000020) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 7, extend_);
      }
      if (((bitField0_ & 0x00000040) != 0)) {
        output.writeInt32(10, type_);
      }
      if (((bitField0_ & 0x00000080) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 15, content_);
      }
      if (((bitField0_ & 0x00000100) != 0)) {
        output.writeBytes(20, bytesContent_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, ops_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, code_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, msg_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, target_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, msgId_);
      }
      if (((bitField0_ & 0x00000020) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, extend_);
      }
      if (((bitField0_ & 0x00000040) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(10, type_);
      }
      if (((bitField0_ & 0x00000080) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(15, content_);
      }
      if (((bitField0_ & 0x00000100) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(20, bytesContent_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof top.pin90.friend.chatserver.protocol.WSMsg.Msg)) {
        return super.equals(obj);
      }
      top.pin90.friend.chatserver.protocol.WSMsg.Msg other = (top.pin90.friend.chatserver.protocol.WSMsg.Msg) obj;

      if (hasOps() != other.hasOps()) return false;
      if (hasOps()) {
        if (getOps()
            != other.getOps()) return false;
      }
      if (hasCode() != other.hasCode()) return false;
      if (hasCode()) {
        if (getCode()
            != other.getCode()) return false;
      }
      if (hasMsg() != other.hasMsg()) return false;
      if (hasMsg()) {
        if (!getMsg()
            .equals(other.getMsg())) return false;
      }
      if (hasTarget() != other.hasTarget()) return false;
      if (hasTarget()) {
        if (!getTarget()
            .equals(other.getTarget())) return false;
      }
      if (hasMsgId() != other.hasMsgId()) return false;
      if (hasMsgId()) {
        if (!getMsgId()
            .equals(other.getMsgId())) return false;
      }
      if (hasExtend() != other.hasExtend()) return false;
      if (hasExtend()) {
        if (!getExtend()
            .equals(other.getExtend())) return false;
      }
      if (hasType() != other.hasType()) return false;
      if (hasType()) {
        if (getType()
            != other.getType()) return false;
      }
      if (hasContent() != other.hasContent()) return false;
      if (hasContent()) {
        if (!getContent()
            .equals(other.getContent())) return false;
      }
      if (hasBytesContent() != other.hasBytesContent()) return false;
      if (hasBytesContent()) {
        if (!getBytesContent()
            .equals(other.getBytesContent())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasOps()) {
        hash = (37 * hash) + OPS_FIELD_NUMBER;
        hash = (53 * hash) + getOps();
      }
      if (hasCode()) {
        hash = (37 * hash) + CODE_FIELD_NUMBER;
        hash = (53 * hash) + getCode();
      }
      if (hasMsg()) {
        hash = (37 * hash) + MSG_FIELD_NUMBER;
        hash = (53 * hash) + getMsg().hashCode();
      }
      if (hasTarget()) {
        hash = (37 * hash) + TARGET_FIELD_NUMBER;
        hash = (53 * hash) + getTarget().hashCode();
      }
      if (hasMsgId()) {
        hash = (37 * hash) + MSG_ID_FIELD_NUMBER;
        hash = (53 * hash) + getMsgId().hashCode();
      }
      if (hasExtend()) {
        hash = (37 * hash) + EXTEND_FIELD_NUMBER;
        hash = (53 * hash) + getExtend().hashCode();
      }
      if (hasType()) {
        hash = (37 * hash) + TYPE_FIELD_NUMBER;
        hash = (53 * hash) + getType();
      }
      if (hasContent()) {
        hash = (37 * hash) + CONTENT_FIELD_NUMBER;
        hash = (53 * hash) + getContent().hashCode();
      }
      if (hasBytesContent()) {
        hash = (37 * hash) + BYTES_CONTENT_FIELD_NUMBER;
        hash = (53 * hash) + getBytesContent().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static top.pin90.friend.chatserver.protocol.WSMsg.Msg parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static top.pin90.friend.chatserver.protocol.WSMsg.Msg parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static top.pin90.friend.chatserver.protocol.WSMsg.Msg parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static top.pin90.friend.chatserver.protocol.WSMsg.Msg parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static top.pin90.friend.chatserver.protocol.WSMsg.Msg parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static top.pin90.friend.chatserver.protocol.WSMsg.Msg parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static top.pin90.friend.chatserver.protocol.WSMsg.Msg parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static top.pin90.friend.chatserver.protocol.WSMsg.Msg parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static top.pin90.friend.chatserver.protocol.WSMsg.Msg parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static top.pin90.friend.chatserver.protocol.WSMsg.Msg parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static top.pin90.friend.chatserver.protocol.WSMsg.Msg parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static top.pin90.friend.chatserver.protocol.WSMsg.Msg parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(top.pin90.friend.chatserver.protocol.WSMsg.Msg prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protocol.Msg}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:protocol.Msg)
        top.pin90.friend.chatserver.protocol.WSMsg.MsgOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return top.pin90.friend.chatserver.protocol.WSMsg.internal_static_protocol_Msg_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return top.pin90.friend.chatserver.protocol.WSMsg.internal_static_protocol_Msg_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                top.pin90.friend.chatserver.protocol.WSMsg.Msg.class, top.pin90.friend.chatserver.protocol.WSMsg.Msg.Builder.class);
      }

      // Construct using top.pin90.friend.chatserver.protocol.WSMsg.Msg.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        ops_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        code_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        msg_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        target_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        msgId_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        extend_ = "";
        bitField0_ = (bitField0_ & ~0x00000020);
        type_ = 0;
        bitField0_ = (bitField0_ & ~0x00000040);
        content_ = "";
        bitField0_ = (bitField0_ & ~0x00000080);
        bytesContent_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000100);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return top.pin90.friend.chatserver.protocol.WSMsg.internal_static_protocol_Msg_descriptor;
      }

      @java.lang.Override
      public top.pin90.friend.chatserver.protocol.WSMsg.Msg getDefaultInstanceForType() {
        return top.pin90.friend.chatserver.protocol.WSMsg.Msg.getDefaultInstance();
      }

      @java.lang.Override
      public top.pin90.friend.chatserver.protocol.WSMsg.Msg build() {
        top.pin90.friend.chatserver.protocol.WSMsg.Msg result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public top.pin90.friend.chatserver.protocol.WSMsg.Msg buildPartial() {
        top.pin90.friend.chatserver.protocol.WSMsg.Msg result = new top.pin90.friend.chatserver.protocol.WSMsg.Msg(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.ops_ = ops_;
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.code_ = code_;
          to_bitField0_ |= 0x00000002;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          to_bitField0_ |= 0x00000004;
        }
        result.msg_ = msg_;
        if (((from_bitField0_ & 0x00000008) != 0)) {
          to_bitField0_ |= 0x00000008;
        }
        result.target_ = target_;
        if (((from_bitField0_ & 0x00000010) != 0)) {
          to_bitField0_ |= 0x00000010;
        }
        result.msgId_ = msgId_;
        if (((from_bitField0_ & 0x00000020) != 0)) {
          to_bitField0_ |= 0x00000020;
        }
        result.extend_ = extend_;
        if (((from_bitField0_ & 0x00000040) != 0)) {
          result.type_ = type_;
          to_bitField0_ |= 0x00000040;
        }
        if (((from_bitField0_ & 0x00000080) != 0)) {
          to_bitField0_ |= 0x00000080;
        }
        result.content_ = content_;
        if (((from_bitField0_ & 0x00000100) != 0)) {
          to_bitField0_ |= 0x00000100;
        }
        result.bytesContent_ = bytesContent_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof top.pin90.friend.chatserver.protocol.WSMsg.Msg) {
          return mergeFrom((top.pin90.friend.chatserver.protocol.WSMsg.Msg)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(top.pin90.friend.chatserver.protocol.WSMsg.Msg other) {
        if (other == top.pin90.friend.chatserver.protocol.WSMsg.Msg.getDefaultInstance()) return this;
        if (other.hasOps()) {
          setOps(other.getOps());
        }
        if (other.hasCode()) {
          setCode(other.getCode());
        }
        if (other.hasMsg()) {
          bitField0_ |= 0x00000004;
          msg_ = other.msg_;
          onChanged();
        }
        if (other.hasTarget()) {
          bitField0_ |= 0x00000008;
          target_ = other.target_;
          onChanged();
        }
        if (other.hasMsgId()) {
          bitField0_ |= 0x00000010;
          msgId_ = other.msgId_;
          onChanged();
        }
        if (other.hasExtend()) {
          bitField0_ |= 0x00000020;
          extend_ = other.extend_;
          onChanged();
        }
        if (other.hasType()) {
          setType(other.getType());
        }
        if (other.hasContent()) {
          bitField0_ |= 0x00000080;
          content_ = other.content_;
          onChanged();
        }
        if (other.hasBytesContent()) {
          setBytesContent(other.getBytesContent());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        top.pin90.friend.chatserver.protocol.WSMsg.Msg parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (top.pin90.friend.chatserver.protocol.WSMsg.Msg) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int ops_ ;
      /**
       * <pre>
       * 是要进行的操作
       * </pre>
       *
       * <code>optional int32 ops = 1;</code>
       * @return Whether the ops field is set.
       */
      @java.lang.Override
      public boolean hasOps() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <pre>
       * 是要进行的操作
       * </pre>
       *
       * <code>optional int32 ops = 1;</code>
       * @return The ops.
       */
      @java.lang.Override
      public int getOps() {
        return ops_;
      }
      /**
       * <pre>
       * 是要进行的操作
       * </pre>
       *
       * <code>optional int32 ops = 1;</code>
       * @param value The ops to set.
       * @return This builder for chaining.
       */
      public Builder setOps(int value) {
        bitField0_ |= 0x00000001;
        ops_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 是要进行的操作
       * </pre>
       *
       * <code>optional int32 ops = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearOps() {
        bitField0_ = (bitField0_ & ~0x00000001);
        ops_ = 0;
        onChanged();
        return this;
      }

      private int code_ ;
      /**
       * <code>optional int32 code = 2;</code>
       * @return Whether the code field is set.
       */
      @java.lang.Override
      public boolean hasCode() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>optional int32 code = 2;</code>
       * @return The code.
       */
      @java.lang.Override
      public int getCode() {
        return code_;
      }
      /**
       * <code>optional int32 code = 2;</code>
       * @param value The code to set.
       * @return This builder for chaining.
       */
      public Builder setCode(int value) {
        bitField0_ |= 0x00000002;
        code_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 code = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearCode() {
        bitField0_ = (bitField0_ & ~0x00000002);
        code_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object msg_ = "";
      /**
       * <code>optional string msg = 3;</code>
       * @return Whether the msg field is set.
       */
      public boolean hasMsg() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>optional string msg = 3;</code>
       * @return The msg.
       */
      public java.lang.String getMsg() {
        java.lang.Object ref = msg_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            msg_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string msg = 3;</code>
       * @return The bytes for msg.
       */
      public com.google.protobuf.ByteString
          getMsgBytes() {
        java.lang.Object ref = msg_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          msg_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string msg = 3;</code>
       * @param value The msg to set.
       * @return This builder for chaining.
       */
      public Builder setMsg(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        msg_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string msg = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearMsg() {
        bitField0_ = (bitField0_ & ~0x00000004);
        msg_ = getDefaultInstance().getMsg();
        onChanged();
        return this;
      }
      /**
       * <code>optional string msg = 3;</code>
       * @param value The bytes for msg to set.
       * @return This builder for chaining.
       */
      public Builder setMsgBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        msg_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object target_ = "";
      /**
       * <pre>
       * 消息的目标
       * </pre>
       *
       * <code>optional string target = 5;</code>
       * @return Whether the target field is set.
       */
      public boolean hasTarget() {
        return ((bitField0_ & 0x00000008) != 0);
      }
      /**
       * <pre>
       * 消息的目标
       * </pre>
       *
       * <code>optional string target = 5;</code>
       * @return The target.
       */
      public java.lang.String getTarget() {
        java.lang.Object ref = target_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            target_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * 消息的目标
       * </pre>
       *
       * <code>optional string target = 5;</code>
       * @return The bytes for target.
       */
      public com.google.protobuf.ByteString
          getTargetBytes() {
        java.lang.Object ref = target_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          target_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 消息的目标
       * </pre>
       *
       * <code>optional string target = 5;</code>
       * @param value The target to set.
       * @return This builder for chaining.
       */
      public Builder setTarget(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        target_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 消息的目标
       * </pre>
       *
       * <code>optional string target = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearTarget() {
        bitField0_ = (bitField0_ & ~0x00000008);
        target_ = getDefaultInstance().getTarget();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 消息的目标
       * </pre>
       *
       * <code>optional string target = 5;</code>
       * @param value The bytes for target to set.
       * @return This builder for chaining.
       */
      public Builder setTargetBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        target_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object msgId_ = "";
      /**
       * <pre>
       *消息的唯一标识符
       * </pre>
       *
       * <code>optional string msg_id = 6;</code>
       * @return Whether the msgId field is set.
       */
      public boolean hasMsgId() {
        return ((bitField0_ & 0x00000010) != 0);
      }
      /**
       * <pre>
       *消息的唯一标识符
       * </pre>
       *
       * <code>optional string msg_id = 6;</code>
       * @return The msgId.
       */
      public java.lang.String getMsgId() {
        java.lang.Object ref = msgId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            msgId_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *消息的唯一标识符
       * </pre>
       *
       * <code>optional string msg_id = 6;</code>
       * @return The bytes for msgId.
       */
      public com.google.protobuf.ByteString
          getMsgIdBytes() {
        java.lang.Object ref = msgId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          msgId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *消息的唯一标识符
       * </pre>
       *
       * <code>optional string msg_id = 6;</code>
       * @param value The msgId to set.
       * @return This builder for chaining.
       */
      public Builder setMsgId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        msgId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *消息的唯一标识符
       * </pre>
       *
       * <code>optional string msg_id = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearMsgId() {
        bitField0_ = (bitField0_ & ~0x00000010);
        msgId_ = getDefaultInstance().getMsgId();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *消息的唯一标识符
       * </pre>
       *
       * <code>optional string msg_id = 6;</code>
       * @param value The bytes for msgId to set.
       * @return This builder for chaining.
       */
      public Builder setMsgIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        msgId_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object extend_ = "";
      /**
       * <pre>
       * 扩展字段
       * </pre>
       *
       * <code>optional string extend = 7;</code>
       * @return Whether the extend field is set.
       */
      public boolean hasExtend() {
        return ((bitField0_ & 0x00000020) != 0);
      }
      /**
       * <pre>
       * 扩展字段
       * </pre>
       *
       * <code>optional string extend = 7;</code>
       * @return The extend.
       */
      public java.lang.String getExtend() {
        java.lang.Object ref = extend_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            extend_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * 扩展字段
       * </pre>
       *
       * <code>optional string extend = 7;</code>
       * @return The bytes for extend.
       */
      public com.google.protobuf.ByteString
          getExtendBytes() {
        java.lang.Object ref = extend_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          extend_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 扩展字段
       * </pre>
       *
       * <code>optional string extend = 7;</code>
       * @param value The extend to set.
       * @return This builder for chaining.
       */
      public Builder setExtend(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        extend_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 扩展字段
       * </pre>
       *
       * <code>optional string extend = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearExtend() {
        bitField0_ = (bitField0_ & ~0x00000020);
        extend_ = getDefaultInstance().getExtend();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 扩展字段
       * </pre>
       *
       * <code>optional string extend = 7;</code>
       * @param value The bytes for extend to set.
       * @return This builder for chaining.
       */
      public Builder setExtendBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        extend_ = value;
        onChanged();
        return this;
      }

      private int type_ ;
      /**
       * <pre>
       * 内容的类型
       * </pre>
       *
       * <code>optional int32 type = 10;</code>
       * @return Whether the type field is set.
       */
      @java.lang.Override
      public boolean hasType() {
        return ((bitField0_ & 0x00000040) != 0);
      }
      /**
       * <pre>
       * 内容的类型
       * </pre>
       *
       * <code>optional int32 type = 10;</code>
       * @return The type.
       */
      @java.lang.Override
      public int getType() {
        return type_;
      }
      /**
       * <pre>
       * 内容的类型
       * </pre>
       *
       * <code>optional int32 type = 10;</code>
       * @param value The type to set.
       * @return This builder for chaining.
       */
      public Builder setType(int value) {
        bitField0_ |= 0x00000040;
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 内容的类型
       * </pre>
       *
       * <code>optional int32 type = 10;</code>
       * @return This builder for chaining.
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000040);
        type_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object content_ = "";
      /**
       * <pre>
       * 字符串内容
       * </pre>
       *
       * <code>optional string content = 15;</code>
       * @return Whether the content field is set.
       */
      public boolean hasContent() {
        return ((bitField0_ & 0x00000080) != 0);
      }
      /**
       * <pre>
       * 字符串内容
       * </pre>
       *
       * <code>optional string content = 15;</code>
       * @return The content.
       */
      public java.lang.String getContent() {
        java.lang.Object ref = content_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            content_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * 字符串内容
       * </pre>
       *
       * <code>optional string content = 15;</code>
       * @return The bytes for content.
       */
      public com.google.protobuf.ByteString
          getContentBytes() {
        java.lang.Object ref = content_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          content_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 字符串内容
       * </pre>
       *
       * <code>optional string content = 15;</code>
       * @param value The content to set.
       * @return This builder for chaining.
       */
      public Builder setContent(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000080;
        content_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 字符串内容
       * </pre>
       *
       * <code>optional string content = 15;</code>
       * @return This builder for chaining.
       */
      public Builder clearContent() {
        bitField0_ = (bitField0_ & ~0x00000080);
        content_ = getDefaultInstance().getContent();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 字符串内容
       * </pre>
       *
       * <code>optional string content = 15;</code>
       * @param value The bytes for content to set.
       * @return This builder for chaining.
       */
      public Builder setContentBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000080;
        content_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString bytesContent_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <pre>
       * 字节内容
       * </pre>
       *
       * <code>optional bytes bytes_content = 20;</code>
       * @return Whether the bytesContent field is set.
       */
      @java.lang.Override
      public boolean hasBytesContent() {
        return ((bitField0_ & 0x00000100) != 0);
      }
      /**
       * <pre>
       * 字节内容
       * </pre>
       *
       * <code>optional bytes bytes_content = 20;</code>
       * @return The bytesContent.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getBytesContent() {
        return bytesContent_;
      }
      /**
       * <pre>
       * 字节内容
       * </pre>
       *
       * <code>optional bytes bytes_content = 20;</code>
       * @param value The bytesContent to set.
       * @return This builder for chaining.
       */
      public Builder setBytesContent(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000100;
        bytesContent_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 字节内容
       * </pre>
       *
       * <code>optional bytes bytes_content = 20;</code>
       * @return This builder for chaining.
       */
      public Builder clearBytesContent() {
        bitField0_ = (bitField0_ & ~0x00000100);
        bytesContent_ = getDefaultInstance().getBytesContent();
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:protocol.Msg)
    }

    // @@protoc_insertion_point(class_scope:protocol.Msg)
    private static final top.pin90.friend.chatserver.protocol.WSMsg.Msg DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new top.pin90.friend.chatserver.protocol.WSMsg.Msg();
    }

    public static top.pin90.friend.chatserver.protocol.WSMsg.Msg getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<Msg>
        PARSER = new com.google.protobuf.AbstractParser<Msg>() {
      @java.lang.Override
      public Msg parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Msg(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Msg> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Msg> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public top.pin90.friend.chatserver.protocol.WSMsg.Msg getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protocol_Msg_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protocol_Msg_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013WSMsg.proto\022\010protocol\"\223\001\n\003Msg\022\013\n\003ops\030\001" +
      " \001(\005\022\014\n\004code\030\002 \001(\005\022\013\n\003msg\030\003 \001(\t\022\016\n\006targe" +
      "t\030\005 \001(\t\022\016\n\006msg_id\030\006 \001(\t\022\016\n\006extend\030\007 \001(\t\022" +
      "\014\n\004type\030\n \001(\005\022\017\n\007content\030\017 \001(\t\022\025\n\rbytes_" +
      "content\030\024 \001(\014B-\n$top.pin90.friend.chatse" +
      "rver.protocolB\005WSMsg"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_protocol_Msg_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_protocol_Msg_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protocol_Msg_descriptor,
        new java.lang.String[] { "Ops", "Code", "Msg", "Target", "MsgId", "Extend", "Type", "Content", "BytesContent", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
