// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ResProto.proto

package top.pin90.friend.chatserver.protocol.res;

public final class ResProto {
  private ResProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface BaseResOrBuilder extends
      // @@protoc_insertion_point(interface_extends:protocol.BaseRes)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *要进行的操作
     * </pre>
     *
     * <code>required int32 result = 1;</code>
     * @return Whether the result field is set.
     */
    boolean hasResult();
    /**
     * <pre>
     *要进行的操作
     * </pre>
     *
     * <code>required int32 result = 1;</code>
     * @return The result.
     */
    int getResult();

    /**
     * <pre>
     *要进行的操作
     * </pre>
     *
     * <code>optional int32 ops = 2;</code>
     * @return Whether the ops field is set.
     */
    boolean hasOps();
    /**
     * <pre>
     *要进行的操作
     * </pre>
     *
     * <code>optional int32 ops = 2;</code>
     * @return The ops.
     */
    int getOps();

    /**
     * <pre>
     * 内容的类型
     * </pre>
     *
     * <code>optional int32 type = 5;</code>
     * @return Whether the type field is set.
     */
    boolean hasType();
    /**
     * <pre>
     * 内容的类型
     * </pre>
     *
     * <code>optional int32 type = 5;</code>
     * @return The type.
     */
    int getType();

    /**
     * <pre>
     * 字符串内容
     * </pre>
     *
     * <code>optional string content = 6;</code>
     * @return Whether the content field is set.
     */
    boolean hasContent();
    /**
     * <pre>
     * 字符串内容
     * </pre>
     *
     * <code>optional string content = 6;</code>
     * @return The content.
     */
    java.lang.String getContent();
    /**
     * <pre>
     * 字符串内容
     * </pre>
     *
     * <code>optional string content = 6;</code>
     * @return The bytes for content.
     */
    com.google.protobuf.ByteString
        getContentBytes();

    /**
     * <pre>
     * 字节内容
     * </pre>
     *
     * <code>optional bytes bytesContent = 7;</code>
     * @return Whether the bytesContent field is set.
     */
    boolean hasBytesContent();
    /**
     * <pre>
     * 字节内容
     * </pre>
     *
     * <code>optional bytes bytesContent = 7;</code>
     * @return The bytesContent.
     */
    com.google.protobuf.ByteString getBytesContent();

    /**
     * <pre>
     * uri路径
     * </pre>
     *
     * <code>optional string uri = 10;</code>
     * @return Whether the uri field is set.
     */
    boolean hasUri();
    /**
     * <pre>
     * uri路径
     * </pre>
     *
     * <code>optional string uri = 10;</code>
     * @return The uri.
     */
    java.lang.String getUri();
    /**
     * <pre>
     * uri路径
     * </pre>
     *
     * <code>optional string uri = 10;</code>
     * @return The bytes for uri.
     */
    com.google.protobuf.ByteString
        getUriBytes();
  }
  /**
   * Protobuf type {@code protocol.BaseRes}
   */
  public static final class BaseRes extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:protocol.BaseRes)
      BaseResOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use BaseRes.newBuilder() to construct.
    private BaseRes(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private BaseRes() {
      content_ = "";
      bytesContent_ = com.google.protobuf.ByteString.EMPTY;
      uri_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new BaseRes();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private BaseRes(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              bitField0_ |= 0x00000001;
              result_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              ops_ = input.readInt32();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000004;
              type_ = input.readInt32();
              break;
            }
            case 50: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000008;
              content_ = bs;
              break;
            }
            case 58: {
              bitField0_ |= 0x00000010;
              bytesContent_ = input.readBytes();
              break;
            }
            case 82: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000020;
              uri_ = bs;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ResProto.internal_static_protocol_BaseRes_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ResProto.internal_static_protocol_BaseRes_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ResProto.BaseRes.class, ResProto.BaseRes.Builder.class);
    }

    private int bitField0_;
    public static final int RESULT_FIELD_NUMBER = 1;
    private int result_;
    /**
     * <pre>
     *要进行的操作
     * </pre>
     *
     * <code>required int32 result = 1;</code>
     * @return Whether the result field is set.
     */
    @java.lang.Override
    public boolean hasResult() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <pre>
     *要进行的操作
     * </pre>
     *
     * <code>required int32 result = 1;</code>
     * @return The result.
     */
    @java.lang.Override
    public int getResult() {
      return result_;
    }

    public static final int OPS_FIELD_NUMBER = 2;
    private int ops_;
    /**
     * <pre>
     *要进行的操作
     * </pre>
     *
     * <code>optional int32 ops = 2;</code>
     * @return Whether the ops field is set.
     */
    @java.lang.Override
    public boolean hasOps() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <pre>
     *要进行的操作
     * </pre>
     *
     * <code>optional int32 ops = 2;</code>
     * @return The ops.
     */
    @java.lang.Override
    public int getOps() {
      return ops_;
    }

    public static final int TYPE_FIELD_NUMBER = 5;
    private int type_;
    /**
     * <pre>
     * 内容的类型
     * </pre>
     *
     * <code>optional int32 type = 5;</code>
     * @return Whether the type field is set.
     */
    @java.lang.Override
    public boolean hasType() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <pre>
     * 内容的类型
     * </pre>
     *
     * <code>optional int32 type = 5;</code>
     * @return The type.
     */
    @java.lang.Override
    public int getType() {
      return type_;
    }

    public static final int CONTENT_FIELD_NUMBER = 6;
    private volatile java.lang.Object content_;
    /**
     * <pre>
     * 字符串内容
     * </pre>
     *
     * <code>optional string content = 6;</code>
     * @return Whether the content field is set.
     */
    @java.lang.Override
    public boolean hasContent() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <pre>
     * 字符串内容
     * </pre>
     *
     * <code>optional string content = 6;</code>
     * @return The content.
     */
    @java.lang.Override
    public java.lang.String getContent() {
      java.lang.Object ref = content_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          content_ = s;
        }
        return s;
      }
    }
    /**
     * <pre>
     * 字符串内容
     * </pre>
     *
     * <code>optional string content = 6;</code>
     * @return The bytes for content.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getContentBytes() {
      java.lang.Object ref = content_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        content_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int BYTESCONTENT_FIELD_NUMBER = 7;
    private com.google.protobuf.ByteString bytesContent_;
    /**
     * <pre>
     * 字节内容
     * </pre>
     *
     * <code>optional bytes bytesContent = 7;</code>
     * @return Whether the bytesContent field is set.
     */
    @java.lang.Override
    public boolean hasBytesContent() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <pre>
     * 字节内容
     * </pre>
     *
     * <code>optional bytes bytesContent = 7;</code>
     * @return The bytesContent.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getBytesContent() {
      return bytesContent_;
    }

    public static final int URI_FIELD_NUMBER = 10;
    private volatile java.lang.Object uri_;
    /**
     * <pre>
     * uri路径
     * </pre>
     *
     * <code>optional string uri = 10;</code>
     * @return Whether the uri field is set.
     */
    @java.lang.Override
    public boolean hasUri() {
      return ((bitField0_ & 0x00000020) != 0);
    }
    /**
     * <pre>
     * uri路径
     * </pre>
     *
     * <code>optional string uri = 10;</code>
     * @return The uri.
     */
    @java.lang.Override
    public java.lang.String getUri() {
      java.lang.Object ref = uri_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          uri_ = s;
        }
        return s;
      }
    }
    /**
     * <pre>
     * uri路径
     * </pre>
     *
     * <code>optional string uri = 10;</code>
     * @return The bytes for uri.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getUriBytes() {
      java.lang.Object ref = uri_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        uri_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasResult()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeInt32(1, result_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeInt32(2, ops_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        output.writeInt32(5, type_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, content_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        output.writeBytes(7, bytesContent_);
      }
      if (((bitField0_ & 0x00000020) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 10, uri_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, result_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, ops_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, type_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, content_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(7, bytesContent_);
      }
      if (((bitField0_ & 0x00000020) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(10, uri_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ResProto.BaseRes)) {
        return super.equals(obj);
      }
      ResProto.BaseRes other = (ResProto.BaseRes) obj;

      if (hasResult() != other.hasResult()) return false;
      if (hasResult()) {
        if (getResult()
            != other.getResult()) return false;
      }
      if (hasOps() != other.hasOps()) return false;
      if (hasOps()) {
        if (getOps()
            != other.getOps()) return false;
      }
      if (hasType() != other.hasType()) return false;
      if (hasType()) {
        if (getType()
            != other.getType()) return false;
      }
      if (hasContent() != other.hasContent()) return false;
      if (hasContent()) {
        if (!getContent()
            .equals(other.getContent())) return false;
      }
      if (hasBytesContent() != other.hasBytesContent()) return false;
      if (hasBytesContent()) {
        if (!getBytesContent()
            .equals(other.getBytesContent())) return false;
      }
      if (hasUri() != other.hasUri()) return false;
      if (hasUri()) {
        if (!getUri()
            .equals(other.getUri())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasResult()) {
        hash = (37 * hash) + RESULT_FIELD_NUMBER;
        hash = (53 * hash) + getResult();
      }
      if (hasOps()) {
        hash = (37 * hash) + OPS_FIELD_NUMBER;
        hash = (53 * hash) + getOps();
      }
      if (hasType()) {
        hash = (37 * hash) + TYPE_FIELD_NUMBER;
        hash = (53 * hash) + getType();
      }
      if (hasContent()) {
        hash = (37 * hash) + CONTENT_FIELD_NUMBER;
        hash = (53 * hash) + getContent().hashCode();
      }
      if (hasBytesContent()) {
        hash = (37 * hash) + BYTESCONTENT_FIELD_NUMBER;
        hash = (53 * hash) + getBytesContent().hashCode();
      }
      if (hasUri()) {
        hash = (37 * hash) + URI_FIELD_NUMBER;
        hash = (53 * hash) + getUri().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ResProto.BaseRes parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ResProto.BaseRes parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ResProto.BaseRes parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ResProto.BaseRes parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ResProto.BaseRes parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ResProto.BaseRes parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ResProto.BaseRes parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ResProto.BaseRes parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static ResProto.BaseRes parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static ResProto.BaseRes parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ResProto.BaseRes parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ResProto.BaseRes parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ResProto.BaseRes prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protocol.BaseRes}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:protocol.BaseRes)
        ResProto.BaseResOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ResProto.internal_static_protocol_BaseRes_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ResProto.internal_static_protocol_BaseRes_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ResProto.BaseRes.class, ResProto.BaseRes.Builder.class);
      }

      // Construct using top.pin90.friend.chatserver.protocol.res.ResProto.BaseRes.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        result_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        ops_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        type_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        content_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        bytesContent_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000010);
        uri_ = "";
        bitField0_ = (bitField0_ & ~0x00000020);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ResProto.internal_static_protocol_BaseRes_descriptor;
      }

      @java.lang.Override
      public ResProto.BaseRes getDefaultInstanceForType() {
        return ResProto.BaseRes.getDefaultInstance();
      }

      @java.lang.Override
      public ResProto.BaseRes build() {
        ResProto.BaseRes result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public ResProto.BaseRes buildPartial() {
        ResProto.BaseRes result = new ResProto.BaseRes(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.result_ = result_;
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.ops_ = ops_;
          to_bitField0_ |= 0x00000002;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.type_ = type_;
          to_bitField0_ |= 0x00000004;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          to_bitField0_ |= 0x00000008;
        }
        result.content_ = content_;
        if (((from_bitField0_ & 0x00000010) != 0)) {
          to_bitField0_ |= 0x00000010;
        }
        result.bytesContent_ = bytesContent_;
        if (((from_bitField0_ & 0x00000020) != 0)) {
          to_bitField0_ |= 0x00000020;
        }
        result.uri_ = uri_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ResProto.BaseRes) {
          return mergeFrom((ResProto.BaseRes)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ResProto.BaseRes other) {
        if (other == ResProto.BaseRes.getDefaultInstance()) return this;
        if (other.hasResult()) {
          setResult(other.getResult());
        }
        if (other.hasOps()) {
          setOps(other.getOps());
        }
        if (other.hasType()) {
          setType(other.getType());
        }
        if (other.hasContent()) {
          bitField0_ |= 0x00000008;
          content_ = other.content_;
          onChanged();
        }
        if (other.hasBytesContent()) {
          setBytesContent(other.getBytesContent());
        }
        if (other.hasUri()) {
          bitField0_ |= 0x00000020;
          uri_ = other.uri_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        if (!hasResult()) {
          return false;
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ResProto.BaseRes parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ResProto.BaseRes) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int result_ ;
      /**
       * <pre>
       *要进行的操作
       * </pre>
       *
       * <code>required int32 result = 1;</code>
       * @return Whether the result field is set.
       */
      @java.lang.Override
      public boolean hasResult() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <pre>
       *要进行的操作
       * </pre>
       *
       * <code>required int32 result = 1;</code>
       * @return The result.
       */
      @java.lang.Override
      public int getResult() {
        return result_;
      }
      /**
       * <pre>
       *要进行的操作
       * </pre>
       *
       * <code>required int32 result = 1;</code>
       * @param value The result to set.
       * @return This builder for chaining.
       */
      public Builder setResult(int value) {
        bitField0_ |= 0x00000001;
        result_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *要进行的操作
       * </pre>
       *
       * <code>required int32 result = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearResult() {
        bitField0_ = (bitField0_ & ~0x00000001);
        result_ = 0;
        onChanged();
        return this;
      }

      private int ops_ ;
      /**
       * <pre>
       *要进行的操作
       * </pre>
       *
       * <code>optional int32 ops = 2;</code>
       * @return Whether the ops field is set.
       */
      @java.lang.Override
      public boolean hasOps() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <pre>
       *要进行的操作
       * </pre>
       *
       * <code>optional int32 ops = 2;</code>
       * @return The ops.
       */
      @java.lang.Override
      public int getOps() {
        return ops_;
      }
      /**
       * <pre>
       *要进行的操作
       * </pre>
       *
       * <code>optional int32 ops = 2;</code>
       * @param value The ops to set.
       * @return This builder for chaining.
       */
      public Builder setOps(int value) {
        bitField0_ |= 0x00000002;
        ops_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *要进行的操作
       * </pre>
       *
       * <code>optional int32 ops = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearOps() {
        bitField0_ = (bitField0_ & ~0x00000002);
        ops_ = 0;
        onChanged();
        return this;
      }

      private int type_ ;
      /**
       * <pre>
       * 内容的类型
       * </pre>
       *
       * <code>optional int32 type = 5;</code>
       * @return Whether the type field is set.
       */
      @java.lang.Override
      public boolean hasType() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <pre>
       * 内容的类型
       * </pre>
       *
       * <code>optional int32 type = 5;</code>
       * @return The type.
       */
      @java.lang.Override
      public int getType() {
        return type_;
      }
      /**
       * <pre>
       * 内容的类型
       * </pre>
       *
       * <code>optional int32 type = 5;</code>
       * @param value The type to set.
       * @return This builder for chaining.
       */
      public Builder setType(int value) {
        bitField0_ |= 0x00000004;
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 内容的类型
       * </pre>
       *
       * <code>optional int32 type = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000004);
        type_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object content_ = "";
      /**
       * <pre>
       * 字符串内容
       * </pre>
       *
       * <code>optional string content = 6;</code>
       * @return Whether the content field is set.
       */
      public boolean hasContent() {
        return ((bitField0_ & 0x00000008) != 0);
      }
      /**
       * <pre>
       * 字符串内容
       * </pre>
       *
       * <code>optional string content = 6;</code>
       * @return The content.
       */
      public java.lang.String getContent() {
        java.lang.Object ref = content_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            content_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * 字符串内容
       * </pre>
       *
       * <code>optional string content = 6;</code>
       * @return The bytes for content.
       */
      public com.google.protobuf.ByteString
          getContentBytes() {
        java.lang.Object ref = content_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          content_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 字符串内容
       * </pre>
       *
       * <code>optional string content = 6;</code>
       * @param value The content to set.
       * @return This builder for chaining.
       */
      public Builder setContent(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        content_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 字符串内容
       * </pre>
       *
       * <code>optional string content = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearContent() {
        bitField0_ = (bitField0_ & ~0x00000008);
        content_ = getDefaultInstance().getContent();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 字符串内容
       * </pre>
       *
       * <code>optional string content = 6;</code>
       * @param value The bytes for content to set.
       * @return This builder for chaining.
       */
      public Builder setContentBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        content_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString bytesContent_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <pre>
       * 字节内容
       * </pre>
       *
       * <code>optional bytes bytesContent = 7;</code>
       * @return Whether the bytesContent field is set.
       */
      @java.lang.Override
      public boolean hasBytesContent() {
        return ((bitField0_ & 0x00000010) != 0);
      }
      /**
       * <pre>
       * 字节内容
       * </pre>
       *
       * <code>optional bytes bytesContent = 7;</code>
       * @return The bytesContent.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getBytesContent() {
        return bytesContent_;
      }
      /**
       * <pre>
       * 字节内容
       * </pre>
       *
       * <code>optional bytes bytesContent = 7;</code>
       * @param value The bytesContent to set.
       * @return This builder for chaining.
       */
      public Builder setBytesContent(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        bytesContent_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 字节内容
       * </pre>
       *
       * <code>optional bytes bytesContent = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearBytesContent() {
        bitField0_ = (bitField0_ & ~0x00000010);
        bytesContent_ = getDefaultInstance().getBytesContent();
        onChanged();
        return this;
      }

      private java.lang.Object uri_ = "";
      /**
       * <pre>
       * uri路径
       * </pre>
       *
       * <code>optional string uri = 10;</code>
       * @return Whether the uri field is set.
       */
      public boolean hasUri() {
        return ((bitField0_ & 0x00000020) != 0);
      }
      /**
       * <pre>
       * uri路径
       * </pre>
       *
       * <code>optional string uri = 10;</code>
       * @return The uri.
       */
      public java.lang.String getUri() {
        java.lang.Object ref = uri_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            uri_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * uri路径
       * </pre>
       *
       * <code>optional string uri = 10;</code>
       * @return The bytes for uri.
       */
      public com.google.protobuf.ByteString
          getUriBytes() {
        java.lang.Object ref = uri_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          uri_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * uri路径
       * </pre>
       *
       * <code>optional string uri = 10;</code>
       * @param value The uri to set.
       * @return This builder for chaining.
       */
      public Builder setUri(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        uri_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * uri路径
       * </pre>
       *
       * <code>optional string uri = 10;</code>
       * @return This builder for chaining.
       */
      public Builder clearUri() {
        bitField0_ = (bitField0_ & ~0x00000020);
        uri_ = getDefaultInstance().getUri();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * uri路径
       * </pre>
       *
       * <code>optional string uri = 10;</code>
       * @param value The bytes for uri to set.
       * @return This builder for chaining.
       */
      public Builder setUriBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        uri_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:protocol.BaseRes)
    }

    // @@protoc_insertion_point(class_scope:protocol.BaseRes)
    private static final ResProto.BaseRes DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ResProto.BaseRes();
    }

    public static ResProto.BaseRes getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<BaseRes>
        PARSER = new com.google.protobuf.AbstractParser<BaseRes>() {
      @java.lang.Override
      public BaseRes parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new BaseRes(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<BaseRes> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<BaseRes> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public ResProto.BaseRes getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protocol_BaseRes_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protocol_BaseRes_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016ResProto.proto\022\010protocol\"h\n\007BaseRes\022\016\n" +
      "\006result\030\001 \002(\005\022\013\n\003ops\030\002 \001(\005\022\014\n\004type\030\005 \001(\005" +
      "\022\017\n\007content\030\006 \001(\t\022\024\n\014bytesContent\030\007 \001(\014\022" +
      "\013\n\003uri\030\n \001(\tB0\n$top.pin90.friend.chatser" +
      "ver.protocolB\010ResProto"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_protocol_BaseRes_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_protocol_BaseRes_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protocol_BaseRes_descriptor,
        new java.lang.String[] { "Result", "Ops", "Type", "Content", "BytesContent", "Uri", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
