id: 1
server:
  port: 910${id}
spring:
  application:
    name: chat-top.pin90.friend.routeserverapi.service
  redis:
    host: 192.168.0.111
chat:
  server:
    port: 1000${id}
zookeeper:
  connectString: 192.168.0.111:2181
auth:
  jwt:
    secret: 123456
    userIdKey: userId
    iss: pin
  token:
    key: token
logging:
  level:
    top:
      pin90:
        friend:
          chatserver: debug


